apiVersion: v1
kind: Service
metadata:
  name: finance-tracker-service
spec:
  type: NodePort
  selector:
    app: finance-tracker
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30001

    
