apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finance-tracker-ingress
spec:
  rules:
    - host: finance.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: finance-tracker-service
                port:
                  number: 5000
